type: taskWindows
actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
agent: WIN-DQDML0OOTPU - AGNT0002
agentCluster:
agentClusterVar:
agentVar:
avgRunTime: 0
avgRunTimeDisplay: 0 Seconds
broadcastCluster:
broadcastClusterVar:
command: dir
commandOrScript: Command
cpDuration:
cpDurationUnit: Minutes
createConsole: false
credentials: Administrator
credentialsVar:
customField1:
  label:
  value:
customField2:
  label:
  value:
desktopInteract: false
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration:
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
elevateUser: false
enforceVariables: false
environment: []
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exitCodeOutput:
exitCodeProcessing: Success Exitcode Range
exitCodeText:
exitCodes: 0-2
exportReleaseLevel: 7.9.0.0
exportTable: ops_task_windows
firstRun: 2025-10-17 16:21:17 +0200
holdResources: false
lastRun: 2026-01-15 13:38:10 +0100
lastRunTime: 0
lastRunTimeDisplay: 0 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration:
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
lockVariables: false
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 2
maxRunTimeDisplay: 2 Seconds
minRunTime: 0
minRunTimeDisplay: 0 Seconds
name: WIN The file name is ${ops_trigger_file_name_simple}
notes: []
opswiseGroups: []
outputFailureOnly: false
outputReturnFile:
outputReturnNline: '100'
outputReturnSline: '1'
outputReturnText:
outputReturnType: OUTERR
outputType: STDOUT
overrideInstanceWait: "No"
parameters:
resPriority: 10
resPriorityVar:
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate:
restrictionPeriodAfterTime:
restrictionPeriodBeforeDate:
restrictionPeriodBeforeTime:
restrictionPeriodDateList: []
retainSysIds: true
retryExitCodes:
retryIndefinitely: false
retryInterval: 60
retryMaximum: 0
retrySuppressFailure: false
runCount: 62
runTime: 3
runtimeDir:
script:
simulation: false
startHeld: false
startHeldReason:
summary:
sysId: 05a1dc0824934a9bad9f5ec4065f4592
timeZonePref: -- System Default --
twDelayAmount: '20'
twDelayDuration: 00:00:00:00
twDelayType: Seconds
twWaitAmount:
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
userEstimatedDuration:
variables: []
version: 18
virtualResources: []
waitForOutput: true
